server:
  port: 8686
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_ssm?serverTimezone=Asia/Shanghai
    username: root
    password: 123
mybatis:
  type-aliases-package: com.hlb.vue_ssm_demo.pojo
